[phases.setup]
nixPkgs = ["nodejs_20", "python3", "cairo", "pango", "libjpeg", "giflib"]

[phases.install]
cmds = [
  "npm ci --omit=dev --ignore-scripts",
  "npm install --save-dev typescript @types/node",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
